name: ci-cd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    #----------------------------------------------
    #       os and node versions to test on
    #----------------------------------------------
    strategy:
      matrix:
        node-version: [16.16.0]
    runs-on: ubuntu-latest

    steps:
      #----------------------------------------------
      #       check-out repo and set-up node
      #----------------------------------------------
      - name: Set up NodeJS ${{ matrix.node-version }}
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check-out repository
        uses: actions/checkout@v3

      #----------------------------------------------
      #       install dependencies
      #----------------------------------------------
      - name: Install dependencies
        run: npm install

      #----------------------------------------------
      #       run tests
      #----------------------------------------------
      - name: Lint code
        run: npm run lint

      - name: Test with mocha
        run: npm run coverage

      #----------------------------------------------
      #       build
      #----------------------------------------------
      - name: Build code
        run: npm run build

      #----------------------------------------------
      #              reporting
      #----------------------------------------------

      - name: Use Codecov to track coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/clover.xml
          fail_ci_if_error: false
          verbose: true

  # cd:
  #   # Only run this job if the "ci" job passes
  #   needs: ci

  #   # Only run this job if new work is merged into the "main" branch
  #   if: (github.event_name == 'push' || github.event.pull_request.merged == true) && github.ref == 'refs/heads/main'

  #   #----------------------------------------------
  #   #       os and node versions to test on
  #   #----------------------------------------------
  #   runs-on: ubuntu-latest

  #   # Define job steps
  #   steps:
  #     #----------------------------------------------
  #     #       check-out repo and set-up node
  #     #----------------------------------------------
  #     - name: Set up NodeJS ${{ matrix.node-version }}
  #       id: setup-node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}

  #     - name: Check-out repository
  #       uses: actions/checkout@v3
