name: Data release cron job
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # (every day at 1am)
    - cron:  '0 1 * * *'

permissions:
  contents: read

jobs:
  data:
    runs-on: ubuntu-latest
    container: node:16
    environment: cron

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tweet script
        run: npm run data