name: Data release cron job
on:
  schedule:
    # POSIX syntax: Minute [0,59] Hour [0,23] Day [1,31] Month [1,12] Day of week [0 (Sunday),6]
    - cron:  '0 1 * * *'

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.CF_CRON_URL }}
          method: 'POST'