name: Data release cron job
on:
  schedule:
    # POSIX syntax: Minute [0,59] Hour [0,23] Day [1,31] Month [1,12] Day of week [0 (Sunday),6]
    - cron:  '0 1 * * *'

permissions:
  contents: read

jobs:
  data:
    runs-on: ubuntu-latest
    container: node:16
    environment: cron

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run data script
        run: npm run data